### PR TITLE
Support CrystaX NDK for Android builds

### PR DESCRIPTION
**Pull request by ghost**
https://www.crystax.net/android/ndk

### CODE REVIEW

**Comment by crystax** [comment]
Is anything wrong with this PR? It was submitted eight days ago, but still no any reaction.

**Comment by minggo** [comment]
Why use crystax ndk?

**Comment by crystax** [comment]
Well, CrystaX NDK is alternative for Google's NDK, offering many additional features for Android developers. Main goal of CrystaX NDK is POSIX conformance (which is obviously not the case for Google's NDK). This makes many peoples using CrystaX NDK for Android native development instead of Google's one. It would be good to allow such people use Cocos2d-x in their environment out-of-the-box, not enforcing them hack Cocos2d-x sources.

In fact, CrystaX NDK is developed in a way to be drop-in replacement for Google's NDK, so Cocos2d-x successfully builds with CrystaX NDK with minor changes provided by this pull request. As you can see, these changes are just changes in build script, not in sources itself - and this prove the fact that CrystaX NDK works as drop-in replacement of Google's NDK.

So taking into account all above, I don't see why not allow your users use NDK for theirs choice. If they want use Google's NDK - ok, they can right now; but what if they need for some reason use CrystaX NDK? Currently, they are enforced to somehow mimic CrystaX NDK to Google's one (replacing RELEASE.TXT in NDK root to make Cocos2d-x build scripts happy) or hack Cocos2d-x sources. In my opinion, it would be better to just allow them use CrystaX NDK "as is", especially taking into account that there is no changes required in Cocos2d-x sources.

**Comment by linshun** [comment]
Thanks @crystax 
It will be released in the coming version on 9th Nov.

**Comment by minggo** [comment]
@crystax I send a pull request to simplify selecting toolchain version in #342 . I don' t know why there are special logic for crystax, and i haven't heard from developers that using crystax.

Please fix it if you have simple way to support crystax.

**Pull request merged**
