### PR TITLE
Update plugins/project_deploy.py

### PR DESCRIPTION
**Pull request by tttreal**
"cocos run" for android, change uninstall&&install to reinstall for keeping data on device

### CODE REVIEW

**Comment by tttreal** [comment]
Also see http://discuss.cocos2d-x.org/t/android-saved-data-are-erased-by-cocos-compile/21704/3

**Comment by natural-law** [comment]
@tttreal 
In fact, current implementation consider the situation:
The sign of the application on the device is different with the apk will be installed.

In that situation, the apk will not be installed with `reinstall`.

**Comment by tttreal** [comment]
@natural-law 

Thank you for your replying.

I don't think that case you mentioned, but yet, I like this implementation.
Because all developers can uninstall manually in that case, but, not all developers know reinstall option (-r).
So, I think reinstall is better for almost everyone, if not all.

Are you cocos developer?
I want to leave it up to your judgement :)
Please close or merge ( ´ ▽ ` )

**Comment by natural-law** [comment]
@tttreal 
Yep, I think your suggestion is right. But I will take a test of your idea:
Can I detect the failure of `adb install -r`? Because if the `reinstall` is failed, the command should be terminated.

I will optimize the implementation after the test.
After all, thanks for your feedback & suggestion.

PS:
I'm the developer of console, and I will close the PR once my implementation is merged.

**Comment by natural-law** [comment]
@tttreal 
Hi, I have taken the test. When the sign are different between the app on device & the apk will be installed. The `adb install -r` will be failed. But the exit code is always 0.
So, I can't detect the failure. Also I can't terminate the process of `cocos command`.

In that situation, there will be a problem:
When I'm running `cocos run ...` command. The generated apk is not installed, but the app on the device is running.
The developer will be confused about the appearance of the running application.

So I'm sorry that I can't change the implementation now.
After all, thanks for your contribution!

**Comment by tttreal** [comment]
@natural-law 

Thank you for your testing!
And I'm sold for the situation, it's not good.
Current implementation is better.
I'll close this PR ;)

**Pull request closed without merging**
