### PR TITLE
FirefoxOS support

### PR DESCRIPTION
**Pull request by nrbrd**
Support to build Firefox OS package. Now it's almost the same that the Web, but while FOS has permissions, plugins, APIs and others, it's better to separate the support to this device.

### CODE REVIEW

**Comment by nrbrd** [comment]
No FOS support?

**Comment by nrbrd** [comment]
Firefox OS webmanifest was merged to Cocos2d-js development branch https://github.com/cocos2d/cocos2d-js/pull/1255 And I believe that this official support should be very useful. I'm a Firefox OS developer, and using the web version is not so good. If you need something before continue with this support, please, just let me know, so I'll try to help it.

**Comment by minggo** [comment]
@aron-bordin 
I don't know that Cocos2d-js needs it.
@pandamicro 
Could you please take a look?

@aron-bordin 
We are on holidays for Chinese Spring Festival.
We will be back on Feb.25.

**Comment by pandamicro** [comment]
Hi, Minggo, We did merged Aron's PR for better Firefox OS support, because it doesn't affect any other platforms. But it's an official supported platform, @aron-bordin, I'm afraid we don't have time to maintain the Firefox OS support, that's the reason that it can't be official.

Whether it's ok to support Firefox OS with Cocos Console? I have no idea. I understand @minggo 's worry, we can't support `cocos compile -p firefoxos` while we know that we won't maintain it. In the meantime, Cocos2d is an open source project, we welcome the community to contribute and help us maintain the project, so if @aron-bordin can maintain it, maybe it's also useful for those who need this feature.

@minggo what do you think ?

**Comment by nrbrd** [comment]
@pandamicro Thx for your feedback. Of course that I'd love to maintain it, but now I understand better your worries.

**Pull request closed without merging**
