### PR TITLE
Update gen libs

### PR DESCRIPTION
**Pull request by minggo**

### CODE REVIEW

**Comment by Anywhere-Music-Player** [comment]
Cool. Any comments? Like summary description how to use and what result to expect?

**Comment by minggo** [comment]
just add an option `-l [cpp | js | lua]`, default is `cpp`

**Comment by minggo** [comment]
please give some feedback after your usage

**Comment by Anywhere-Music-Player** [comment]
@minggo 
I've used just `cocos gen-libs -p mac`, because anyway checked what was modified, can't wait)
And as default option is cpp and default mode debug, what is right. 
Build took only 4min on my 2013 old Intel Core i3. Thats really saving time 👍 don't remember exactly how much was before, but I guess around 15min. 
Thank you. 

p.s. another thing I have in my mind is generating prebuilt libs for android. I'm using Android Studio and compile my game in it, but using prebuilt libs, same as for Xcode. Is there any updates about this for android? Like was fixed need of "tools" folder hack and all now compiles  with latest NDK, tools version .. well just everything latest, when you updating it in Android Studio?

**Comment by minggo** [comment]
Yep, android is updated too. Now proj.android is expected as an Android Studio project. You can just use `cocos gen-libs -p=android`, but make sure proj.android is an Android Studio project, which is named `proj.android-studio`.

**Comment by Anywhere-Music-Player** [comment]
Thats nice. But.. I have some configured project for my game already.. and used prebuilt for it, but with hacks. Maybe you can create some topic with quick tutorial about android? Like how to start a new project and use prebuilts for it? Because currently I don’t understand how to do it in right way.. maybe my current project setup is wrong.. for iOS I have no problems with prebuilts, setup is flawless.

**Comment by minggo** [comment]
I update console just to keep compatibility, i don't want developers to use prebuilt libs, and there is not template for it now.

**Comment by Anywhere-Music-Player** [comment]
But prebuilts is saving time a lot and disk space. Each game project doesn’t contains cocos git with all source code files, thats about 2.3Gb each project. Compare to just project with prebuilts it’s just up to 10Mb and it’s easy to use overall. If you so archive in Xcode - for prebuilts it will do fast compile, but with full source code it will recompile all cocos source code each time you archive build.

**Pull request merged**
