### PR TITLE
Linux jsbcc support.

### PR DESCRIPTION
**Pull request by azmeuk**
Fixes jscompile plugin and brings linux support.

### CODE REVIEW

**Comment by azmeuk** [comment]
Is there something more I should do to see this commit merged ?

**Comment by minggo** [comment]
Sorry. We don't want to support JSB on linux. It will bring more work to the community. We must focus on other important features.

**Comment by azmeuk** [comment]
Ricardo Quesada's spidermonkey is compilable on Linux, and JSB is [already supported](https://github.com/cocos2d/cocos2d-x/pull/5339).
There is absolutely no modification to bring to the code to support JSB on Linux. The only thing needed is to keep the CMakeFiles updated.
Don't you think the further work to support Linux is tiny enough to be official ?

**Comment by natural-law** [comment]
@azmeuk 
The source code of `jscc` will be moved to another repository :
https://github.com/cocos2d-html5/JSCompiler

I will close this PR, you can send PR to the new repository. And we can discuss it later.
Thank you!

**Pull request closed without merging**
