### PR TITLE
Launch the Mac app without using 'open'

### PR DESCRIPTION
**Pull request by twhittock**
This allows the user to see stdout from the run application.

### CODE REVIEW

**Comment by natural-law** [comment]
@twhittock,
Could you tell me the reason of the modification? I'm not sure the advantage of the PR.
Thanks very much!

**Comment by twhittock** [comment]
It allows the user to see stdout (cclog etc) - without this, there doesn't seem to be a way to see log output. It also allows us to see return codes from the run application - if it fails to launch then more information is available. Not sure what you mean by PR.

**Comment by natural-law** [comment]
The PR means pull request.
Do you mean launch the app with `open` will show the cclog messages?
But I think it's better if the cclog messages are visible for developers.
Maybe the PR needs more developers opinion.

**Comment by twhittock** [comment]
no - using `open` does NOT show cclog messages, which is why I made this change. Without this change, cclog messages are NOT shown on mac.

**Comment by natural-law** [comment]
Thanks for your contribution. But it's better use `target name` instead of `project name`.
I have optimized the logic code and send another PR :https://github.com/cocos2d/cocos2d-console/pull/102

Thank you very much!

**Comment by twhittock** [comment]
cool thanks - but please see my comment in the other pull request, as the target name does not really have a '\' character in it.

**Pull request closed without merging**
