### PR TITLE
rase exception when run cocos package fail

### PR DESCRIPTION
**Pull request by hugohuang1111**

### CODE REVIEW

**Comment by GuoLunHao** [comment]
@pandamicro @natural-law please review this commit

**Comment by natural-law** [comment]
@GuoLunHao 
What's the purpose of the PR? Only want to raise Exception when running `sdkbox` failed?
 If you want to make the result code of `cocos package` command is same with `sdkbox` command, please using `raise cocos.CCPluginError(ERROR_MSG, ERROR_NO)`.

Another issue: If you keep using raise Exception, please make the error message be compatible with Multi-Language. Please take a look at `bin/MultiLanguage.py` for the implementation.

**Comment by hugohuang1111** [comment]
@natural-law

**Comment by natural-law** [comment]
@linshun @pandamicro 
It's OK for merge.

**Comment by letzgame** [comment]
Please remove from the mail list.Thanks,

**Pull request merged**
