### PR TITLE
Support CocoaPods workspace.

### PR DESCRIPTION
**Pull request by xpol**
CocoaPods is useful when add 3rd party libraries and SDKs for iOS and OS X.
So it is worth add support for cocos2d-x projects to use CocoaPods.

Here is currently implemented:
1. Check `Podfile` exists in proj.ios_mac.
2. Check the CocoaPods workspace has the same base name with `xcodeproj`.
3. If 1 and 2 are both satisfied, the `cocos compile -p [ios|mac]` will use CocoaPods workspace for build rather than  `xcodeproj`.

### CODE REVIEW

**Comment by thuydx55** [comment]
@pandamicro Please merge this PR

**Comment by xpol** [comment]
Thanks!

**Comment by gsempe** [comment]
Can we please get this PR merged if it is still alright?
Cocoapods support is almost mandatory in iOS/OSX world

**Comment by natural-law** [comment]
The PR is LGTM. Thanks for your contribution. And sorry for the late reply.

**Pull request merged**
